// const patients = [
//   { name: "Aad", surname: "Groen", gender: "male", region: "Netherlands" },
//   {
//     name: "Harm van der",
//     surname: "Pol",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Pieter", surname: "Meijer", gender: "male", region: "Netherlands" },
//   {
//     name: "Michiel",
//     surname: "Gerritsen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Sander van",
//     surname: "Wijk",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Olaf de", surname: "Ruiter", gender: "male", region: "Netherlands" },
//   { name: "Teun de", surname: "Wit", gender: "male", region: "Netherlands" },
//   { name: "Tom", surname: "Schouten", gender: "male", region: "Netherlands" },
//   {
//     name: "Mirthe",
//     surname: "Meijer",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Lisa", surname: "Kok", gender: "female", region: "Netherlands" },
//   { name: "Emiel de", surname: "Vos", gender: "male", region: "Netherlands" },
//   {
//     name: "Diewertje van",
//     surname: "Loon",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Arjan van",
//     surname: "Vliet",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Femke", surname: "Meijer", gender: "female", region: "Netherlands" },
//   {
//     name: "Lonneke",
//     surname: "Sanders",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Christien",
//     surname: "Prins",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Mathijs", surname: "Mol", gender: "male", region: "Netherlands" },
//   { name: "Carlijn", surname: "Bos", gender: "female", region: "Netherlands" },
//   {
//     name: "Eelco van der",
//     surname: "Meer",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Willemijn",
//     surname: "Hofman",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Reinout van der",
//     surname: "Veen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Lotte",
//     surname: "Hoekstra",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Aart", surname: "Willems", gender: "male", region: "Netherlands" },
//   { name: "Florus", surname: "Prins", gender: "male", region: "Netherlands" },
//   {
//     name: "Valentijn",
//     surname: "Gerritsen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Paul de", surname: "Vos", gender: "male", region: "Netherlands" },
//   { name: "Henk", surname: "Postma", gender: "male", region: "Netherlands" },
//   {
//     name: "Willemijn van",
//     surname: "Dijk",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Boudewijn van",
//     surname: "Dijk",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Jaap de", surname: "Ruiter", gender: "male", region: "Netherlands" },
//   {
//     name: "Floor van",
//     surname: "Veen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Tom de", surname: "Leeuw", gender: "male", region: "Netherlands" },
//   {
//     name: "Heleen van",
//     surname: "Loon",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Luuk", surname: "Hermans", gender: "male", region: "Netherlands" },
//   {
//     name: "Huib van der",
//     surname: "Veen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Jaap", surname: "Hoekstra", gender: "male", region: "Netherlands" },
//   {
//     name: "Mathijs van",
//     surname: "Dijk",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Peter de",
//     surname: "Koning",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Maartje",
//     surname: "Schouten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Thomas van", surname: "Dam", gender: "male", region: "Netherlands" },
//   { name: "Huib", surname: "Verhoeven", gender: "male", region: "Netherlands" },
//   {
//     name: "Imke van",
//     surname: "Dongen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Maartje",
//     surname: "Kramer",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Willemijn van",
//     surname: "Dongen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Daan",
//     surname: "Timmermans",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Tom", surname: "Huisman", gender: "male", region: "Netherlands" },
//   {
//     name: "Doortje de",
//     surname: "Bruijn",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Reinout",
//     surname: "Hoekstra",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Victor de",
//     surname: "Graaf",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Ivo van", surname: "Vliet", gender: "male", region: "Netherlands" },
//   {
//     name: "Valentijn",
//     surname: "Evers",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Imke", surname: "Jansen", gender: "female", region: "Netherlands" },
//   {
//     name: "Willemijn de",
//     surname: "Lange",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Luuk", surname: "Mulder", gender: "male", region: "Netherlands" },
//   {
//     name: "Stefan",
//     surname: "Hendriks",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Leentje",
//     surname: "Schouten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Petra de", surname: "Wit", gender: "female", region: "Netherlands" },
//   { name: "Thea", surname: "Kramer", gender: "female", region: "Netherlands" },
//   { name: "Aad", surname: "Koning", gender: "male", region: "Netherlands" },
//   { name: "Aart", surname: "Dekker", gender: "male", region: "Netherlands" },
//   { name: "Quintin", surname: "Jonker", gender: "male", region: "Netherlands" },
//   {
//     name: "Eline van de",
//     surname: "Velde",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Kristien van de",
//     surname: "Velde",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Dirk van der",
//     surname: "Pol",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Kristien",
//     surname: "Scholten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Anna",
//     surname: "Hendriks",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Eva de", surname: "Haan", gender: "female", region: "Netherlands" },
//   { name: "Ivo", surname: "Willems", gender: "male", region: "Netherlands" },
//   { name: "Chris van", surname: "Loon", gender: "male", region: "Netherlands" },
//   {
//     name: "Laura van der",
//     surname: "Meulen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Jack", surname: "Vos", gender: "male", region: "Netherlands" },
//   {
//     name: "Hanneke van",
//     surname: "Veen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Eelco", surname: "Bos", gender: "male", region: "Netherlands" },
//   {
//     name: "Lisa van der",
//     surname: "Horst",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Gerrit",
//     surname: "Hoekstra",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Klaas van der",
//     surname: "Velden",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Femke de",
//     surname: "Graaf",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Tineke",
//     surname: "Scholten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Boudewijn de",
//     surname: "Vries",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Corien de",
//     surname: "Haan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Florus van den",
//     surname: "Berg",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Victor van de",
//     surname: "Velde",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Arjan",
//     surname: "Verhoeven",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Ineke van",
//     surname: "Dam",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Stefan van",
//     surname: "Beek",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Willeke",
//     surname: "Kuijpers",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Suzanne de",
//     surname: "Koning",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Rik", surname: "Smeets", gender: "male", region: "Netherlands" },
//   { name: "Harm", surname: "Bosman", gender: "male", region: "Netherlands" },
//   {
//     name: "Christiaan",
//     surname: "Dekker",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Gerrit", surname: "Jonker", gender: "male", region: "Netherlands" },
//   {
//     name: "Victor",
//     surname: "Timmermans",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Eelco", surname: "Postma", gender: "male", region: "Netherlands" },
//   {
//     name: "Vincent",
//     surname: "Willems",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Rob", surname: "Maas", gender: "male", region: "Netherlands" },
//   { name: "Jan", surname: "Timmermans", gender: "male", region: "Netherlands" },
//   {
//     name: "Leentje de",
//     surname: "Boer",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Lotte", surname: "Vos", gender: "female", region: "Netherlands" },
//   {
//     name: "Twan van der",
//     surname: "Velden",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Tineke",
//     surname: "Willems",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Willemijn van der",
//     surname: "Laan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Aart", surname: "Peters", gender: "male", region: "Netherlands" },
//   {
//     name: "Suzanne",
//     surname: "Smeets",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Lisa", surname: "Smeets", gender: "female", region: "Netherlands" },
//   {
//     name: "Renske van der",
//     surname: "Wal",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Elise", surname: "Dekker", gender: "female", region: "Netherlands" },
//   { name: "Sander", surname: "Smit", gender: "male", region: "Netherlands" },
//   { name: "Wouter", surname: "Groen", gender: "male", region: "Netherlands" },
//   {
//     name: "Stefan de",
//     surname: "Bruin",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Maaike",
//     surname: "Koster",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Quintin",
//     surname: "Kuijpers",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Huib", surname: "Hoekstra", gender: "male", region: "Netherlands" },
//   {
//     name: "Lonneke van",
//     surname: "Dijk",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Camiel de",
//     surname: "Graaf",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Lonneke",
//     surname: "Evers",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Hendrika",
//     surname: "Jacobs",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Thijs", surname: "Wolters", gender: "male", region: "Netherlands" },
//   {
//     name: "Mirthe van",
//     surname: "Dongen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Willemijn",
//     surname: "Smit",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Ineke", surname: "Bakker", gender: "female", region: "Netherlands" },
//   {
//     name: "Noortje van der",
//     surname: "Veen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Anna van der",
//     surname: "Horst",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Corien de",
//     surname: "Bruin",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Sara van",
//     surname: "Vliet",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Lisa van",
//     surname: "Dongen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Corien",
//     surname: "Dekker",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Carlijn van der",
//     surname: "Meulen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Florus van der",
//     surname: "Ven",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Mirthe",
//     surname: "Timmermans",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Luuk", surname: "Verbeek", gender: "male", region: "Netherlands" },
//   {
//     name: "Wies van de",
//     surname: "Velde",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Victor de", surname: "Boer", gender: "male", region: "Netherlands" },
//   {
//     name: "Renske de",
//     surname: "Haan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Christiaan",
//     surname: "Bakker",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Boudewijn",
//     surname: "Jansen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Thomas de",
//     surname: "Lange",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Elise", surname: "Visser", gender: "female", region: "Netherlands" },
//   {
//     name: "Laura",
//     surname: "Kuijpers",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Victor", surname: "Willems", gender: "male", region: "Netherlands" },
//   {
//     name: "Tineke",
//     surname: "Timmermans",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Roos",
//     surname: "Hendriks",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Aad van",
//     surname: "Leeuwen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Aart", surname: "Scholten", gender: "male", region: "Netherlands" },
//   { name: "Rik", surname: "Huisman", gender: "male", region: "Netherlands" },
//   {
//     name: "Mirthe",
//     surname: "Jacobs",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Sara van den",
//     surname: "Berg",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Valentijn",
//     surname: "Hoekstra",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Paul de", surname: "Ruiter", gender: "male", region: "Netherlands" },
//   { name: "Emma", surname: "Koning", gender: "female", region: "Netherlands" },
//   {
//     name: "Emiel",
//     surname: "Vermeulen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Paulien",
//     surname: "Hoekstra",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Wies", surname: "Jonker", gender: "female", region: "Netherlands" },
//   { name: "Michiel", surname: "Meijer", gender: "male", region: "Netherlands" },
//   {
//     name: "Jacolien van der",
//     surname: "Laan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Lotte",
//     surname: "Timmermans",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Christien",
//     surname: "Vos",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Femke", surname: "Kuiper", gender: "female", region: "Netherlands" },
//   { name: "Aart", surname: "Huisman", gender: "male", region: "Netherlands" },
//   { name: "Jaap", surname: "Sanders", gender: "male", region: "Netherlands" },
//   { name: "Gerard", surname: "Willems", gender: "male", region: "Netherlands" },
//   {
//     name: "Kristien de",
//     surname: "Haan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Peter van der",
//     surname: "Pol",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Eefke", surname: "Mulder", gender: "female", region: "Netherlands" },
//   { name: "Bas", surname: "Brouwer", gender: "male", region: "Netherlands" },
//   {
//     name: "Johanneke",
//     surname: "Bakker",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Vincent", surname: "Mulder", gender: "male", region: "Netherlands" },
//   {
//     name: "Ineke van der",
//     surname: "Velden",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Teun van", surname: "Loon", gender: "male", region: "Netherlands" },
//   { name: "Aart", surname: "Smit", gender: "male", region: "Netherlands" },
//   {
//     name: "Paulien",
//     surname: "Hendriks",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Bas van der",
//     surname: "Laan",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Niek", surname: "Bosman", gender: "male", region: "Netherlands" },
//   {
//     name: "Christien de",
//     surname: "Boer",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Lotte", surname: "Groen", gender: "female", region: "Netherlands" },
//   { name: "Niek", surname: "Koning", gender: "male", region: "Netherlands" },
//   {
//     name: "Lieke",
//     surname: "Hermans",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Eefke",
//     surname: "Vermeulen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Emma",
//     surname: "Gerritsen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Thomas",
//     surname: "Vermeulen",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Laurens van der",
//     surname: "Wal",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Lieke", surname: "Kramer", gender: "female", region: "Netherlands" },
//   { name: "Tom de", surname: "Vries", gender: "male", region: "Netherlands" },
//   { name: "Victor", surname: "Smeets", gender: "male", region: "Netherlands" },
//   {
//     name: "Thijs van de",
//     surname: "Velde",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Yasmijn van",
//     surname: "Vliet",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Victor van",
//     surname: "Loon",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Paul", surname: "Hendriks", gender: "male", region: "Netherlands" },
//   { name: "Jan", surname: "Kuiper", gender: "male", region: "Netherlands" },
//   { name: "Camiel", surname: "Brouwer", gender: "male", region: "Netherlands" },
//   { name: "Olaf", surname: "Kuijpers", gender: "male", region: "Netherlands" },
//   {
//     name: "Ido van den",
//     surname: "Heuvel",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Nelleke", surname: "Vos", gender: "female", region: "Netherlands" },
//   {
//     name: "Rob van den",
//     surname: "Brink",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Thijs van",
//     surname: "Vliet",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Ido", surname: "Mulder", gender: "male", region: "Netherlands" },
//   { name: "Teun", surname: "Bakker", gender: "male", region: "Netherlands" },
//   { name: "Kees", surname: "Smit", gender: "male", region: "Netherlands" },
//   {
//     name: "Christien",
//     surname: "Schouten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Bart van der",
//     surname: "Meer",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Lotte van den",
//     surname: "Brink",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Suzanne",
//     surname: "Bakker",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Doortje van den",
//     surname: "Brink",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Tineke de",
//     surname: "Ruiter",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Hanneke",
//     surname: "Wolters",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Kees", surname: "Sanders", gender: "male", region: "Netherlands" },
//   {
//     name: "Geert de",
//     surname: "Ruiter",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Gerard van den",
//     surname: "Berg",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Christien",
//     surname: "Mulder",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Thomas van",
//     surname: "Dijk",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Kees van der",
//     surname: "Horst",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Laura", surname: "Mulder", gender: "female", region: "Netherlands" },
//   {
//     name: "Wouter de",
//     surname: "Ruiter",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Suzanne van den",
//     surname: "Heuvel",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Mirthe",
//     surname: "Kuiper",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Jacolien van",
//     surname: "Wijk",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Laurens", surname: "Bakker", gender: "male", region: "Netherlands" },
//   { name: "Dirk", surname: "Bos", gender: "male", region: "Netherlands" },
//   {
//     name: "Hendrika de",
//     surname: "Ruiter",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Peter de", surname: "Leeuw", gender: "male", region: "Netherlands" },
//   { name: "Chris", surname: "Kramer", gender: "male", region: "Netherlands" },
//   { name: "Thijs de", surname: "Wit", gender: "male", region: "Netherlands" },
//   {
//     name: "Maartje van",
//     surname: "Loon",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Sander de",
//     surname: "Ruiter",
//     gender: "male",
//     region: "Netherlands",
//   },
//   { name: "Evert", surname: "Dekker", gender: "male", region: "Netherlands" },
//   {
//     name: "Hendrika",
//     surname: "Willems",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Lieke van",
//     surname: "Vliet",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Luuk de", surname: "Wit", gender: "male", region: "Netherlands" },
//   {
//     name: "Heleen de",
//     surname: "Haan",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Neeltje",
//     surname: "Schouten",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Niek de", surname: "Groot", gender: "male", region: "Netherlands" },
//   {
//     name: "Tineke",
//     surname: "Kuijpers",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Eelco", surname: "Prins", gender: "male", region: "Netherlands" },
//   {
//     name: "Thea",
//     surname: "Hoekstra",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Arjan van", surname: "Beek", gender: "male", region: "Netherlands" },
//   { name: "Reinout", surname: "Prins", gender: "male", region: "Netherlands" },
//   {
//     name: "Nelleke",
//     surname: "Molenaar",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Niek de", surname: "Graaf", gender: "male", region: "Netherlands" },
//   {
//     name: "Carlijn van der",
//     surname: "Horst",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Eva", surname: "Scholten", gender: "female", region: "Netherlands" },
//   { name: "Pieter", surname: "Jonker", gender: "male", region: "Netherlands" },
//   { name: "Twan", surname: "Vink", gender: "male", region: "Netherlands" },
//   {
//     name: "Femke",
//     surname: "Brouwer",
//     gender: "female",
//     region: "Netherlands",
//   },
//   { name: "Twan de", surname: "Vos", gender: "male", region: "Netherlands" },
//   { name: "Rob", surname: "Vos", gender: "male", region: "Netherlands" },
//   { name: "Michiel de", surname: "Vos", gender: "male", region: "Netherlands" },
//   {
//     name: "Wies van der",
//     surname: "Horst",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Jaap van de",
//     surname: "Velde",
//     gender: "male",
//     region: "Netherlands",
//   },
//   {
//     name: "Johanneke van",
//     surname: "Loon",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Mirthe van",
//     surname: "Veen",
//     gender: "female",
//     region: "Netherlands",
//   },
//   {
//     name: "Leentje",
//     surname: "Wolters",
//     gender: "female",
//     region: "Netherlands",
//   },
// ];

// const getRandomName = () => {
//   const person = patients[Math.floor(Math.random() * 250)];
//   return `${person.name} ${person.surname}`;
// };

// const getRandomTime = () => {
//   let hour;
//   while (true) {
//     hour = Math.floor(Math.random() * 24);
//     if (hour > 7 && hour < 19) {
//       return hour;
//     }
//   }
// };

// const getRandomDay = () => Math.floor(Math.random() * 28) + 1;

// const generateRandomAppointment = () => ({
//   day: getRandomDay(),
//   time: getRandomTime(),
//   patient: getRandomName(),
//   dentist: getRandomName(),
//   assistant: getRandomName(),
// });

// const generateRandomAppointments = num =>
//   Array(num)
//     .fill(0)
//     .map(_ => generateRandomAppointment());

// export { generateRandomAppointments, patients };

const patients = [
    {
      surname: "Eleonore",
      name: "Deathridge",
      email: "edeathridge0@hao123.com",
      phone_number: "+55 244 377 7422",
      year_of_birth: 2013,
    },
    {
      surname: "Tallia",
      name: "Kasparski",
      email: "tkasparski1@sciencedirect.com",
      phone_number: "+86 413 228 8300",
      year_of_birth: 1941,
    },
    {
      surname: "Jody",
      name: "Zimmermeister",
      email: "jzimmermeister2@qq.com",
      phone_number: "+62 697 677 6317",
      year_of_birth: 1983,
    },
    {
      surname: "Sidonia",
      name: "Gallegos",
      email: "sgallegos3@ycombinator.com",
      phone_number: "+48 194 576 7060",
      year_of_birth: 1968,
    },
    {
      surname: "Duncan",
      name: "Jorio",
      email: "djorio4@i2i.jp",
      phone_number: "+241 286 254 8688",
      year_of_birth: 1952,
    },
    {
      surname: "Roxana",
      name: "Bithany",
      email: "rbithany5@abc.net.au",
      phone_number: "+86 116 655 7844",
      year_of_birth: 1939,
    },
    {
      surname: "Viole",
      name: "Donaghie",
      email: "vdonaghie6@tripod.com",
      phone_number: "+62 941 571 2267",
      year_of_birth: 2015,
    },
    {
      surname: "Maryanne",
      name: "Darwen",
      email: "mdarwen7@scientificamerican.com",
      phone_number: "+39 728 518 9941",
      year_of_birth: 1964,
    },
    {
      surname: "Delinda",
      name: "Housbie",
      email: "dhousbie8@narod.ru",
      phone_number: "+351 895 938 3004",
      year_of_birth: 1971,
    },
    {
      surname: "Nikoletta",
      name: "Auguste",
      email: "nauguste9@paginegialle.it",
      phone_number: "+254 756 525 8109",
      year_of_birth: 1970,
    },
    {
      surname: "Fitzgerald",
      name: "Notton",
      email: "fnottona@thetimes.co.uk",
      phone_number: "+233 381 624 4020",
      year_of_birth: 2008,
    },
    {
      surname: "Nolly",
      name: "Sherreard",
      email: "nsherreardb@homestead.com",
      phone_number: "+7 217 487 0179",
      year_of_birth: 1981,
    },
    {
      surname: "Taryn",
      name: "Kuban",
      email: "tkubanc@who.int",
      phone_number: "+505 101 634 1969",
      year_of_birth: 1973,
    },
    {
      surname: "Nikita",
      name: "Monck",
      email: "nmonckd@studiopress.com",
      phone_number: "+57 531 589 6188",
      year_of_birth: 1976,
    },
    {
      surname: "Yoko",
      name: "Farragher",
      email: "yfarraghere@omniture.com",
      phone_number: "+86 504 990 2006",
      year_of_birth: 1944,
    },
    {
      surname: "Lenee",
      name: "Jedrych",
      email: "ljedrychf@histats.com",
      phone_number: "+232 125 763 3725",
      year_of_birth: 1925,
    },
    {
      surname: "Kamilah",
      name: "Metterick",
      email: "kmetterickg@newyorker.com",
      phone_number: "+420 513 264 2466",
      year_of_birth: 1976,
    },
    {
      surname: "Trevar",
      name: "Youthed",
      email: "tyouthedh@ifeng.com",
      phone_number: "+81 780 598 3567",
      year_of_birth: 1992,
    },
    {
      surname: "Beverley",
      name: "Stannah",
      email: "bstannahi@boston.com",
      phone_number: "+62 324 479 0327",
      year_of_birth: 1989,
    },
    {
      surname: "Dennis",
      name: "Molesworth",
      email: "dmolesworthj@ucoz.com",
      phone_number: "+420 631 613 1128",
      year_of_birth: 1944,
    },
    {
      surname: "Bernie",
      name: "Brumpton",
      email: "bbrumptonk@nsw.gov.au",
      phone_number: "+66 668 395 5516",
      year_of_birth: 1940,
    },
    {
      surname: "Alisha",
      name: "Pykett",
      email: "apykettl@freewebs.com",
      phone_number: "+63 133 537 6498",
      year_of_birth: 2004,
    },
    {
      surname: "Griffy",
      name: "Bayne",
      email: "gbaynem@google.ca",
      phone_number: "+33 794 365 3685",
      year_of_birth: 1976,
    },
    {
      surname: "Abeu",
      name: "Corsor",
      email: "acorsorn@rambler.ru",
      phone_number: "+62 632 645 9882",
      year_of_birth: 1927,
    },
    {
      surname: "Buiron",
      name: "McNeice",
      email: "bmcneiceo@europa.eu",
      phone_number: "+55 228 722 0075",
      year_of_birth: 1943,
    },
    {
      surname: "Raimondo",
      name: "Brunetti",
      email: "rbrunettip@parallels.com",
      phone_number: "+263 938 649 2405",
      year_of_birth: 1968,
    },
    {
      surname: "Pammi",
      name: "Seaborn",
      email: "pseabornq@tiny.cc",
      phone_number: "+98 809 658 3667",
      year_of_birth: 1926,
    },
    {
      surname: "Caye",
      name: "Birkmyre",
      email: "cbirkmyrer@auda.org.au",
      phone_number: "+374 380 841 6487",
      year_of_birth: 1936,
    },
    {
      surname: "Olenka",
      name: "Tyt",
      email: "otyts@sakura.ne.jp",
      phone_number: "+86 150 377 7713",
      year_of_birth: 1992,
    },
    {
      surname: "Sophey",
      name: "Sallinger",
      email: "ssallingert@technorati.com",
      phone_number: "+55 303 423 0577",
      year_of_birth: 1980,
    },
    {
      surname: "Gayleen",
      name: "Woodberry",
      email: "gwoodberryu@spiegel.de",
      phone_number: "+63 295 844 6817",
      year_of_birth: 2003,
    },
    {
      surname: "Marylou",
      name: "Tosspell",
      email: "mtosspellv@thetimes.co.uk",
      phone_number: "+62 747 470 2839",
      year_of_birth: 1948,
    },
    {
      surname: "Megen",
      name: "Shorie",
      email: "mshoriew@spotify.com",
      phone_number: "+63 802 985 5161",
      year_of_birth: 1999,
    },
    {
      surname: "Portie",
      name: "Gudyer",
      email: "pgudyerx@shutterfly.com",
      phone_number: "+232 149 133 4651",
      year_of_birth: 1950,
    },
    {
      surname: "Cornelle",
      name: "Huckabe",
      email: "chuckabey@economist.com",
      phone_number: "+86 819 171 2031",
      year_of_birth: 1957,
    },
    {
      surname: "Hortense",
      name: "Hansmann",
      email: "hhansmannz@weather.com",
      phone_number: "+54 117 927 9050",
      year_of_birth: 2017,
    },
    {
      surname: "Nealy",
      name: "Riddall",
      email: "nriddall10@cargocollective.com",
      phone_number: "+86 338 243 5681",
      year_of_birth: 1973,
    },
    {
      surname: "Antons",
      name: "Yurenev",
      email: "ayurenev11@home.pl",
      phone_number: "+351 818 666 0243",
      year_of_birth: 1964,
    },
    {
      surname: "Marilee",
      name: "Belcham",
      email: "mbelcham12@exblog.jp",
      phone_number: "+86 655 919 8196",
      year_of_birth: 1950,
    },
    {
      surname: "Vannie",
      name: "Caldicott",
      email: "vcaldicott13@dot.gov",
      phone_number: "+258 970 316 3227",
      year_of_birth: 2008,
    },
    {
      surname: "Rosemary",
      name: "Dulen",
      email: "rdulen14@pagesperso-orange.fr",
      phone_number: "+55 502 734 3329",
      year_of_birth: 1987,
    },
    {
      surname: "Goran",
      name: "Conachy",
      email: "gconachy15@utexas.edu",
      phone_number: "+230 690 710 3346",
      year_of_birth: 1941,
    },
    {
      surname: "Kennedy",
      name: "Yushmanov",
      email: "kyushmanov16@dropbox.com",
      phone_number: "+380 734 358 8027",
      year_of_birth: 1961,
    },
    {
      surname: "Veronica",
      name: "Greenly",
      email: "vgreenly17@globo.com",
      phone_number: "+7 462 409 9935",
      year_of_birth: 1990,
    },
    {
      surname: "Nicolle",
      name: "Fisby",
      email: "nfisby18@youtube.com",
      phone_number: "+86 327 226 4962",
      year_of_birth: 1958,
    },
    {
      surname: "Shannon",
      name: "Tarren",
      email: "starren19@youtu.be",
      phone_number: "+86 455 432 3951",
      year_of_birth: 1953,
    },
    {
      surname: "Kelbee",
      name: "Bohlmann",
      email: "kbohlmann1a@amazon.de",
      phone_number: "+62 635 757 6470",
      year_of_birth: 1981,
    },
    {
      surname: "Kimberlee",
      name: "Peart",
      email: "kpeart1b@tuttocitta.it",
      phone_number: "+55 362 419 8568",
      year_of_birth: 1928,
    },
    {
      surname: "Zulema",
      name: "Bartos",
      email: "zbartos1c@typepad.com",
      phone_number: "+62 506 821 3530",
      year_of_birth: 1997,
    },
    {
      surname: "Sileas",
      name: "Ure",
      email: "sure1d@wix.com",
      phone_number: "+504 871 701 4997",
      year_of_birth: 1926,
    },
    {
      surname: "Marie",
      name: "Twopenny",
      email: "mtwopenny1e@seesaa.net",
      phone_number: "+7 887 892 8778",
      year_of_birth: 1938,
    },
    {
      surname: "Gare",
      name: "Plews",
      email: "gplews1f@google.de",
      phone_number: "+33 319 805 2683",
      year_of_birth: 2018,
    },
    {
      surname: "Claudio",
      name: "Foster-Smith",
      email: "cfostersmith1g@desdev.cn",
      phone_number: "+351 243 481 5998",
      year_of_birth: 1975,
    },
    {
      surname: "Johnathan",
      name: "Spurrior",
      email: "jspurrior1h@economist.com",
      phone_number: "+351 740 636 1969",
      year_of_birth: 1942,
    },
    {
      surname: "Fenelia",
      name: "Shorie",
      email: "fshorie1i@zdnet.com",
      phone_number: "+7 833 528 9751",
      year_of_birth: 1986,
    },
    {
      surname: "Priscella",
      name: "Spence",
      email: "pspence1j@csmonitor.com",
      phone_number: "+61 139 465 3842",
      year_of_birth: 1931,
    },
    {
      surname: "Antons",
      name: "Bogies",
      email: "abogies1k@ifeng.com",
      phone_number: "+55 290 868 4220",
      year_of_birth: 2004,
    },
    {
      surname: "Suzi",
      name: "Bugs",
      email: "sbugs1l@webnode.com",
      phone_number: "+63 811 519 6813",
      year_of_birth: 1935,
    },
    {
      surname: "Barri",
      name: "Lukovic",
      email: "blukovic1m@technorati.com",
      phone_number: "+62 644 493 3364",
      year_of_birth: 1971,
    },
    {
      surname: "Goran",
      name: "Maharg",
      email: "gmaharg1n@bigcartel.com",
      phone_number: "+63 287 275 4779",
      year_of_birth: 1965,
    },
    {
      surname: "Brittney",
      name: "Jarley",
      email: "bjarley1o@marriott.com",
      phone_number: "+63 282 805 5091",
      year_of_birth: 2003,
    },
    {
      surname: "Farlie",
      name: "Peller",
      email: "fpeller1p@vk.com",
      phone_number: "+62 102 345 8518",
      year_of_birth: 1922,
    },
    {
      surname: "Brook",
      name: "Raye",
      email: "braye1q@ca.gov",
      phone_number: "+86 310 489 7897",
      year_of_birth: 1984,
    },
    {
      surname: "Judah",
      name: "Maxsted",
      email: "jmaxsted1r@facebook.com",
      phone_number: "+93 665 434 8553",
      year_of_birth: 1958,
    },
    {
      surname: "Ettore",
      name: "Chalkly",
      email: "echalkly1s@deviantart.com",
      phone_number: "+33 312 428 4241",
      year_of_birth: 1989,
    },
    {
      surname: "Hilliary",
      name: "Belford",
      email: "hbelford1t@comsenz.com",
      phone_number: "+63 669 309 0351",
      year_of_birth: 1963,
    },
    {
      surname: "Merralee",
      name: "Butner",
      email: "mbutner1u@seattletimes.com",
      phone_number: "+62 660 786 9716",
      year_of_birth: 2007,
    },
    {
      surname: "Katalin",
      name: "Drayson",
      email: "kdrayson1v@histats.com",
      phone_number: "+86 146 416 3933",
      year_of_birth: 2006,
    },
    {
      surname: "Petronille",
      name: "Chave",
      email: "pchave1w@ifeng.com",
      phone_number: "+1 202 530 9384",
      year_of_birth: 1936,
    },
    {
      surname: "Thorpe",
      name: "Bridson",
      email: "tbridson1x@zdnet.com",
      phone_number: "+84 364 170 5906",
      year_of_birth: 2005,
    },
    {
      surname: "Whitaker",
      name: "Hollibone",
      email: "whollibone1y@spotify.com",
      phone_number: "+7 354 417 8360",
      year_of_birth: 1941,
    },
    {
      surname: "Wren",
      name: "Monkton",
      email: "wmonkton1z@columbia.edu",
      phone_number: "+86 891 627 3102",
      year_of_birth: 1951,
    },
    {
      surname: "Ezequiel",
      name: "Iles",
      email: "eiles20@topsy.com",
      phone_number: "+961 997 601 9666",
      year_of_birth: 1951,
    },
    {
      surname: "Will",
      name: "Charkham",
      email: "wcharkham21@stanford.edu",
      phone_number: "+1 126 622 8360",
      year_of_birth: 1931,
    },
    {
      surname: "Beatrice",
      name: "Francklin",
      email: "bfrancklin22@xrea.com",
      phone_number: "+255 680 789 7321",
      year_of_birth: 1954,
    },
    {
      surname: "Latashia",
      name: "Smail",
      email: "lsmail23@bloomberg.com",
      phone_number: "+375 494 112 1641",
      year_of_birth: 1978,
    },
    {
      surname: "Yolande",
      name: "Bickerdicke",
      email: "ybickerdicke24@blog.com",
      phone_number: "+55 125 295 1039",
      year_of_birth: 2008,
    },
    {
      surname: "Elna",
      name: "Haster",
      email: "ehaster25@mit.edu",
      phone_number: "+86 486 377 2574",
      year_of_birth: 1969,
    },
    {
      surname: "Ginger",
      name: "Hoyte",
      email: "ghoyte26@usatoday.com",
      phone_number: "+7 885 566 9051",
      year_of_birth: 1927,
    },
    {
      surname: "Chickie",
      name: "Hospital",
      email: "chospital27@oakley.com",
      phone_number: "+62 710 936 5431",
      year_of_birth: 1997,
    },
    {
      surname: "Elyse",
      name: "Liddle",
      email: "eliddle28@mysql.com",
      phone_number: "+46 333 121 1678",
      year_of_birth: 1935,
    },
    {
      surname: "Dacy",
      name: "Batistelli",
      email: "dbatistelli29@themeforest.net",
      phone_number: "+84 486 759 6342",
      year_of_birth: 1931,
    },
    {
      surname: "Zack",
      name: "Illston",
      email: "zillston2a@phoca.cz",
      phone_number: "+371 467 931 4356",
      year_of_birth: 1939,
    },
    {
      surname: "Sarina",
      name: "Lytell",
      email: "slytell2b@ucoz.com",
      phone_number: "+57 932 348 4689",
      year_of_birth: 1977,
    },
    {
      surname: "Therine",
      name: "Tresise",
      email: "ttresise2c@columbia.edu",
      phone_number: "+63 686 767 6280",
      year_of_birth: 1920,
    },
    {
      surname: "Winston",
      name: "Coveney",
      email: "wcoveney2d@angelfire.com",
      phone_number: "+241 554 897 6342",
      year_of_birth: 1979,
    },
    {
      surname: "Sven",
      name: "Fielders",
      email: "sfielders2e@webnode.com",
      phone_number: "+55 370 580 0562",
      year_of_birth: 1969,
    },
    {
      surname: "Elysia",
      name: "Tossell",
      email: "etossell2f@amazon.co.uk",
      phone_number: "+252 521 532 3760",
      year_of_birth: 1932,
    },
    {
      surname: "Ronny",
      name: "Drohan",
      email: "rdrohan2g@ycombinator.com",
      phone_number: "+62 611 985 9300",
      year_of_birth: 1966,
    },
    {
      surname: "Max",
      name: "Elie",
      email: "melie2h@bluehost.com",
      phone_number: "+57 427 174 0439",
      year_of_birth: 1969,
    },
    {
      surname: "Celka",
      name: "Steers",
      email: "csteers2i@wordpress.com",
      phone_number: "+52 577 694 8466",
      year_of_birth: 1970,
    },
    {
      surname: "Persis",
      name: "Blacksland",
      email: "pblacksland2j@businessinsider.com",
      phone_number: "+86 157 918 7795",
      year_of_birth: 1945,
    },
    {
      surname: "Thelma",
      name: "Folling",
      email: "tfolling2k@youku.com",
      phone_number: "+86 978 674 2124",
      year_of_birth: 1964,
    },
    {
      surname: "Wanda",
      name: "Hoggin",
      email: "whoggin2l@washingtonpost.com",
      phone_number: "+86 900 754 9221",
      year_of_birth: 1985,
    },
  ],
  dentists = [
    {
      surname: "Anestassia",
      name: "Strettle",
      email: "astrettle2o@tandartspraktijkbvt.nl",
      phone_number: "+62 583 149 1324",
      year_of_birth: 1990,
      id: 1,
    },
    {
      surname: "Fenelia",
      name: "Sones",
      email: "fsones2p@tandartspraktijkbvt.nl",
      phone_number: "+7 721 170 0340",
      year_of_birth: 1927,
      id: 2,
    },
    {
      surname: "Lindsey",
      name: "Akam",
      email: "lakam2q@tandartspraktijkbvt.nl",
      phone_number: "+62 211 867 3223",
      year_of_birth: 1928,
      id: 3,
    },
    {
      surname: "Merna",
      name: "Concannon",
      email: "mconcannon2r@tandartspraktijkbvt.nl",
      phone_number: "+48 889 561 2961",
      year_of_birth: 1942,
      id: 4,
    },
  ],
  assistants = [
    {
      surname: "Agnola",
      name: "Goad",
      email: "agoad2m@tandartspraktijkbvt.nl",
      phone_number: "+93 740 946 9904",
      year_of_birth: 1969,
    },
    {
      surname: "Clayborn",
      name: "Gillon",
      email: "tandartspraktijkbvt.nl",
      phone_number: "+86 802 768 6850",
      year_of_birth: 1932,
    },
  ];

const addId = (group) => {
  group.forEach((item, i) => {
    item.id = i + 1;
    item.healthy = true;
  });
};

addId(assistants);
addId(dentists);
addId(patients);

const getRandomPatient = () => {
  const patient = patients[Math.floor(Math.random() * 50)];
  return `${patient.name} ${patient.surname}`;
};

const getRandomDentist = () => {
  const dentist = dentists[Math.floor(Math.random() * dentists.length)];
  return `${dentist.name} ${dentist.surname}`;
};

const getRandomAssistant = () => {
  const assistant = assistants[Math.floor(Math.random() * assistants.length)];
  return `${assistant.name} ${assistant.surname}`;
};

const getRandomTime = () => {
  let hour;
  while (true) {
    hour = Math.floor(Math.random() * 24);
    if (hour > 7 && hour < 19) {
      return hour;
    }
  }
};

const getRandomDay = () => Math.floor(Math.random() * 28) + 1;

const generateRandomAppointment = () => ({
  day: getRandomDay(),
  time: getRandomTime(),
  patient: getRandomPatient(),
  dentist: getRandomDentist(),
  assistant: getRandomAssistant(),
});

const generateRandomAppointments = (num) =>
  Array(num)
    .fill(0)
    .map((_) => generateRandomAppointment());

const totalPatients = patients.length;
const totalDentists = dentists.length;

    const addDropdowns = (id, group) => {
      const options = group;
      let select = document.getElementById(id);
      for (let i = 0; i < options.length; i++) {
        console.log(group.length);
        let opt = options[i].surname;
        console.log(opt);
        let el = document.createElement("option");
        el.text = opt;
        el.value = opt;
        select.add(el);
      }
    };



export {
  generateRandomAppointments,
  dentists,
  assistants,
  patients,
  totalDentists,
  totalPatients,
  addDropdowns,
};
